crail/routes.py
"""Flask blueprint for the application proper.

.. Copyright © 2015, David Maze

This module only contains the URL-routing logic.  While it assumes that,
for instance, a database object is in scope, actually setting that up is
done in :func:`crail.app.make_app`.

.. autodata:: crail_bp
.. autodata:: crail_js
.. autodata:: crail_css

"""
from .actions import draw_card, get_or_create_player
from .globals import current_player
from .models import Card, Contract, db, Game, World
from flask import abort, Blueprint, current_app, jsonify, render_template, \
    request, session
from flask.ext.assets import Bundle


#: Flask blueprint for crayon-rails handlers.
crail_bp = Blueprint('crail', __name__)

#: Flask-Assets bundle for :data:`crail_bp` JavaScript.
crail_js = Bundle('bower_components/jquery/dist/jquery.js',
                  'bower_components/bootstrap/dist/js/bootstrap.js',
                  'bower_components/underscore/underscore.js',
                  'bower_components/js-cookie/src/js.cookie.js',
                  'crail.js',
                  filters='rjsmin', output='gen/packed.js')

#: Flask-Assets bundle for :data:`crail_bp` CSS.
crail_css = Bundle('bower_components/bootstrap/dist/css/bootstrap.css',
                   'bower_components/bootstrap/dist/css/bootstrap-theme.css',
                   filters='cssmin', output='gen/packed.css')


@crail_bp.route('/')
def index():
    """Return the top-level HTML page."""
    return render_template('index.html')


def player_state():
    """Get the current state as a JSON Flask response.

    Most calls will return this, even if it's a little redundant.
    This always includes enough state for the UI to take some action.
    The return is a JSON object, with the following keys:

    `player_id`
      Always present; the numeric player ID if logged in, or ``null``
    `player_name`
      The player's name, if logged in
    `games`
      If logged in but not in a game, a list of current games, each
      with `id`, `world` (name), and `players` (list of names)
    `worlds`
      If logged in but not in a game, a list of available worlds for
      new games, each with `id` and `name`
    `game`
      If logged in and in a game, the name of the world
    `money`
      If logged in and in a game, the amount of money the current player
      has
    `cards`
      If logged in and in a game, the list of cards the current player has.
      Each is a dictionary with `id`, `number` (printed on the card, if
      available), `event` (text, if the card is an event card), and
      `contracts`.  Each contract in turn has `id`, `good`, `city`, and
      `amount`.

    """
    response = {'player_id': None}

    # (Remember current_player will always be a proxy and will never be
    # None, but it could be a proxy to None)
    if not current_player:
        return jsonify(response)

    response['player_id'] = current_player.id
    response['player_name'] = current_player.name

    if not current_player.game:
        response['games'] = [{
            'id': game.id,
            'world': game.world.name,
            'players': [player.name for player in game.players],
        } for game in Game.query.order_by('id')]
        response['worlds'] = [{
            'id': world.id,
            'name': world.name,
        } for world in World.query.order_by('id')]
        return jsonify(response)

    response['game'] = current_player.game.world.name
    response['money'] = current_player.money

    def card_to_dict(card):
        """Translate a card to a JSON dictionary."""
        jcard = {'id': card.id}
        if card.number:
            jcard['number'] = card.number
        if card.event:
            jcard['event'] = card.event
        if card.contracts:
            jcard['contracts'] = [{'id': contract.id,
                                   'good': contract.good.name,
                                   'city': contract.city.name,
                                   'amount': contract.amount}
                                  for contract in card.contracts]
        return jcard

    response['cards'] = [card_to_dict(card) for card in current_player.cards]

    return jsonify(response)


@crail_bp.route('/api/state')
def state():
    """Retrieve the current state."""
    return player_state()


@crail_bp.route('/api/login', methods=['POST'])
def login():
    """Log in to the system.

    This is a purely assertion-based login scheme: any name will be
    accepted with no further credentials.

    The request body is a JSON object with a `name` key giving the
    name to log in as.

    """
    args = request.get_json()
    name = args.get('name', None)
    if not name:
        abort(400)  # bad request

    # Win, find or create a player
    player = get_or_create_player(name)
    db.session.commit()

    session['player_id'] = player.id
    return player_state()


@crail_bp.route('/api/logout', methods=['POST'])
def logout():
    """Log out of the system."""
    if 'player_id' in session:
        del session['player_id']
    return player_state()


@crail_bp.route('/api/game/join', methods=['POST'])
def join_game():
    """Join a game.

    The request body is a JSON object with a key `game`, with the numeric
    game ID.  You must be logged in already.

    """
    if not current_player:
        abort(400)

    args = request.get_json()
    game_id = args.get('game', None)
    if game_id is None:
        abort(400)

    game = Game.query.get(game_id)
    if game is None:
        abort(400)

    current_player.game = game
    db.session.commit()
    return player_state()


@crail_bp.route('/api/game/leave', methods=['POST'])
def leave_game():
    """Leave a game.

    You must be logged in.  This is a no-op (but a successful one) if
    you are not currently in a game.

    """
    if not current_player:
        abort(400)
    current_player.game = None
    db.session.commit()
    return player_state()


@crail_bp.route('/api/game/new', methods=['POST'])
def new_game():
    """Start a new game.

    The request body is a JSON object with a `world` parameter holding
    the numeric world ID.  You must be logged in already, and will
    automatically join the new game.

    """
    if not current_player:
        abort(400)

    args = request.get_json()
    world_id = args.get('world', None)
    if world_id is None:
        abort(400)

    world = World.query.get(world_id)
    if world is None:
        abort(400)

    game = Game(world=world)
    db.session.add(game)
    current_player.game = game
    db.session.commit()
    return player_state()


@crail_bp.route('/api/gain', methods=['POST'])
def gain_money():
    """Increase the amount of money you have.

    The request body is a JSON dictionary with a key `amount`.  You must
    be logged in.

    """
    if not current_player:
        abort(400)

    args = request.get_json()
    amount = args.get('amount', None)
    if amount is None:
        abort(400)

    current_player.money += amount
    db.session.commit()
    return player_state()


@crail_bp.route('/api/spend', methods=['POST'])
def spend_money():
    """Decrease the amount of money you have.

    The request body is a JSON dictionary with a key `amount`.  You must
    be logged in.

    This and :func:`gain_money` are identical except for the sign.  Gaining
    negative money is the same as this.

    """
    if not current_player:
        abort(400)

    args = request.get_json()
    amount = args.get('amount', None)
    if amount is None:
        abort(400)

    current_player.money -= amount
    db.session.commit()
    return player_state()


@crail_bp.route('/api/draw', methods=['POST'])
def draw():
    """Draw a card.

    You must be logged in.  The card is added to your current cards list
    and returned.

    This endpoint currently has no game knowledge.  You will always get
    exactly one more card if it is there to be drawn.  If it is an event
    card this will not draw another; if you already have "enough" cards
    this will not prevent you from continuing to draw.

    """
    player = current_player._get_current_object()
    if not player:
        abort(400)

    card = draw_card(player.game)
    player.cards.append(card)
    db.session.commit()
    return player_state()


@crail_bp.route('/api/discard', methods=['POST'])
def discard():
    """Discard a card.

    The request body is a JSON object with a key `card` with the
    numeric card ID.  You must be logged in.  The card is removed from
    your current cards list.

    This call "completes an event", or is one part of "flushing
    contracts".  In principle this and :func:`gain_money` can "deliver
    a contract", though :func:`complete` is a better way to do it.

    """
    player = current_player._get_current_object()
    if not player:
        abort(400)

    args = request.get_json()
    card_id = args.get('card', None)
    if card_id is None:
        abort(400)

    card = Card.query.get(card_id)
    if card is not None and card in player.cards:
        player.cards.remove(card)
        db.session.commit()
    return player_state()


@crail_bp.route('/api/complete', methods=['POST'])
def complete():
    """Complete a contract.

    The request body is a JSON object with a key `contract` with the
    numeric contract ID.  You must be logged in and in a game.  This
    adds the amount of the contract to your money holding and discards
    the card, but does not draw a new one to replace it.

    """
    player = current_player._get_current_object()
    if not player:
        current_app.logger.error('complete: no current player')
        abort(400)

    args = request.get_json()
    contract_id = args.get('contract', None)
    if contract_id is None:
        current_app.logger.error('complete: no contract ID')
        abort(400)

    contract = Contract.query.get(contract_id)
    for card in contract.cards:
        if player in card.players:

crail/templates/content.html
{# -*- engine: django -*- #}
<div class="hidden" id="main-page">
    <div class="form-horizontal">
        <div class="form-group">
            <label for="money"
                   class="col-xs-4 col-sm-2 col-md-2 col-lg-1 control-label">
                You have
            </label>
            <div class="col-xs-8 col-sm-4 col-md-2 col-lg-3">
                <div class="input-group">
                    <div class="input-group-addon">$</div>
                    <input type="number" class="form-control" id="money"
                           readonly>
                </div>
            </div>
            <div class="col-xs-6 col-sm-3 col-md-4">
                <button class="btn btn-default btn-block" role="button"
                        data-toggle="modal" data-target="#gain-modal">
                    <span class="glyphicon glyphicon-plus"></span>
                    Gain
                </button>
            </div>
            <div class="col-xs-6 col-sm-3 col-md-4">
                <button class="btn btn-default btn-block" role="button"
                        data-toggle="modal" data-target="#spend-modal">
                    <span class="glyphicon glyphicon-minus"></span>
                    Spend
                </button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="list-group" id="cards-list">
                <a href="#" class="list-group-item" id="draw-card-action">
                    <span class="glyphicon glyphicon-gift"></span>
                    Draw another card
                </a>
            </div>
        </div>
    </div>
</div>

crail/templates/contract-confirm.html
{# -*- engine: django -*- #}
{% extends 'dialog.html' %}
{% set tag='contract-confirm' %}
{% block title %}Play contract{% endblock %}
{% block body %}
    <p>Really play:</p>
    <p id="{{ tag }}-id" class="hidden"></p>
    <p id="{{ tag }}-description"></p>
{% endblock %}
{# Take manual action on the "cancel" button #}
{% block footer %}
    <button class="btn btn-default" id="{{ tag }}-cancel">Cancel</button>
    <button class="btn btn-primary" data-dismiss="modal"
            id="{{ tag }}-action">OK</button>
{% endblock %}

crail/templates/contract-discard.html
{# -*- engine: django -*- #}
{% extends 'dialog.html' %}
{% set tag='contract-discard' %}
{% block title %}Discard{% endblock %}
{% block body %}
    <p>Really discard:</p>
    <p id="{{ tag }}-id" class="hidden"></p>
    <p id="{{ tag }}-description"></p>
{% endblock %}
{# Take manual action on the "cancel" button #}
{% block footer %}
    <button class="btn btn-default" id="{{ tag }}-cancel">Cancel</button>
    <button class="btn btn-primary" data-dismiss="modal"
            id="{{ tag }}-action">OK</button>
{% endblock %}

crail/templates/contract.html
{# -*- engine: django -*- #}
{% extends 'dialog.html' %}
{% set tag='contract' %}
{% from 'macros.html' import glyphicon %}
{% block title %}Select contract{% endblock %}
{% block body %}
    <p id="{{ tag }}-card-id" class="hidden"></p>
    <div class="list-group" id="{{ tag }}-list" data-dismiss="modal">
        <a href="#" class="list-group-item" id="{{ tag }}-discard">
            {{ glyphicon('trash') }} Discard this card
        </a>
    </div>
{% endblock %}
{# No "OK" button, every item in the list is clickable #}
{% block footer %}
    <button class="btn btn-default" data-dismiss="modal">Cancel</button>
{% endblock %}

crail/templates/dialog.html
{# -*- engine: django -*- #}
<div class="modal" id="{{ tag }}-modal" role="dialog"
     aria-labelledby="{{ tag }}-title">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="{{ tag }}-title">
                    {%- block title %}{% endblock -%}
                </h4>
            </div>
            <div class="modal-body">
                {%- block body %}{% endblock -%}
            </div>
            <div class="modal-footer">
                {%- block footer %}
                <button class="btn btn-default"
                        data-dismiss="modal">Cancel</button>
                <button class="btn btn-primary"
                        data-dismiss="modal"
                        id="{{ tag }}-action">OK</button>
                {%- endblock %}
            </div>
        </div>
    </div>
</div>

crail/templates/dialogs.html
{# -*- engine: django -*- #}
<div class="modal" id="gain-modal" role="dialog" aria-labelledby="gain-title">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="gain-title">Gain money</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="gain-amount">Amount</label>
                        <input type="number" min="0" pattern="[0-9]*"
                               inputmode="numeric" class="form-control"
                               id="gain-amount" aria-describedby="gain-help">
                        <span id="gain-help" class="help-block">
                            Money gained from sources other than contracts,
                            such as from other players using your rails
                        </span>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button class="button" class="btn btn-default"
                        data-dismiss="modal">Cancel</button>
                <button class="button" class="btn btn-primary"
                        data-dismiss="modal" id="gain-action">OK</button>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="spend-modal" role="dialog" aria-labelledby="spend-title">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="spend-title">Spend money</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="spend-amount">Amount</label>
                        <input type="number" min="0" pattern="[0-9]*"
                               inputmode="numeric" class="form-control"
                               id="spend-amount" aria-describedby="spend-help">
                        <span id="spend-help" class="help-block">
                            Money spent on anything, including construction
                            and paying other players to use their rails
                        </span>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button class="button" class="btn btn-default"
                        data-dismiss="modal">Cancel</button>
                <button class="button" class="btn btn-primary"
                        data-dismiss="modal" id="spend-action">OK</button>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="discard-modal" role="dialog"
     aria-labelledby="discard-title">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="discard-title">Discard</h4>
            </div>
            <div class="modal-body">
                <p>Really discard:</p>
                <p id="discard-id" class="hidden"></p>
                <p id="discard-description"></p>
            </div>
            <div class="modal-footer">
                <button class="button" class="btn btn-default"
                        data-dismiss="modal">Cancel</button>
                <button class="button" class="btn btn-primary"
                        data-dismiss="modal" id="discard-action">OK</button>
            </div>
        </div>
    </div>
</div>

crail/templates/discard.html
{# -*- engine: django -*- #}
{% extends 'dialog.html' %}
{% set tag='discard' %}
    {% block title %}Discard{% endblock %}
    {% block body %}
        <p>Really discard:</p>
        <p id="{{ tag }}-id" class="hidden"></p>
        <p id="{{ tag }}-description"></p>
    {% endblock %}

crail/templates/gain.html
{# -*- engine: django -*- #}
{% extends 'dialog.html' %}
{% set tag='gain' %}
    {% block title %}Gain money{% endblock %}
    {% block body %}
        <form>
            <div class="form-group">
                <label for="{{ tag }}-amount">Amount</label>
                <input type="number" min="0" pattern="[0-9]*"
                       inputmode="numeric" class="form-control"
                       id="{{ tag }}-amount" aria-describedby="{{ tag }}-help">
                <span id="{{ tag }}-help" class="help-block">
                    Money gained from sources other than contracts,
                    such as from other players using your rails
                </span>
            </div>
        </form>
    {% endblock %}

crail/templates/game.html
{# -*- engine: django -*- #}
<div class="panel panel-default hidden" id="game-page">
    <div class="panel-heading">
        <h2>Would you like to play a game?</h2>
    </div>
    <div class="list-group" id="game-list">
        <a href="#" class="list-group-item" id="new-game-action">A new game</a>
    </div>
</div>
        

crail/templates/index.html
{#- -*- engine: django -*- -#}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <title>Crail</title>
        {%- assets "crail_css" %}
        <link rel="stylesheet" href="{{ ASSET_URL }}">
        {%- endassets %}
    </head>
    <body>
        {% include 'navbar.html' %}
        <div class="container">
            {% include 'login.html' %}
            {% include 'game.html' %}
            {% include 'world.html' %}
            {% include 'content.html' %}
        </div>
        {% include 'gain.html' %}
        {% include 'spend.html' %}
        {% include 'discard.html' %}
        {% include 'contract.html' %}
        {% include 'contract-confirm.html' %}
        {% include 'contract-discard.html' %}
        {%- assets "crail_js" %}
        <script src="{{ ASSET_URL }}"></script>
        {%- endassets %}
    </body>
</html>

crail/templates/login.html
{# -*- engine: django -*- #}
<div class="panel panel-default hidden" id="login-page">
    <div class="panel-heading">
        <h2>Who are you?</h2>
    </div>
    <div class="panel-body">
        <form id="login-form">
            <div class="form-group">
                <label for="login-name">Your name</label>
                <input type="text" class="form-control" id="login-name"
                       placeholder="Arthur, King of the Britons">
            </div>
            <a role="button" href="#" id="login-submit" class="btn btn-default">Submit</a>
        </form>
    </div>
</div>

crail/templates/macros.html
{# -*- engine: django -*- #}
{%- macro glyphicon(name) -%}
<span class="glyphicon glyphicon-{{ name }}"></span>
{%- endmacro -%}

crail/templates/navbar.html
{# -*- engine: django -*- #}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse"
                    data-target="#navbar-content">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" id="game-name-control"
               href="{{ url_for('crail.index') }}">Crail</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-content">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle hidden"
                       id="user-control"
                       data-toggle="dropdown" role="button"
                       aria-expanded="false">
                        <span id="name-control">Me</span>
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#" id="leave-game-action">Leave game</a></li>
                        <li><a href="#" id="logout-action">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

crail/templates/world.html
{# -*- engine: django -*- #}
<div class="panel panel-default hidden" id="world-page">
    <div class="panel-heading">
        <h2>Which game?</h2>
    </div>
    <div class="list-group" id="world-list">
        <a href="#" class="list-group-item" id="old-game-action">
            Back to game listing
        </a>
    </div>
</div>
        